### ISSUE TITLE
[Feature] VS-Code extension-pack with all of our extensions

### ISSUE THREAD

**Issue by Hafflgav** [FlowSquad/miranum-ide#119]
- [x] Description created
- [x] Reviewed by peer: @peterhnm 
- [x] Prioritised

# Description
We want to have an extension pack listed in the vs-code marketplace which includes all the necessary miranum-plugins to get started with developing a process application. This helps the user to just "pick all" instead of finding the right one. Especially with a growing amount of extensions that can come in handy. 

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] Create VS Code extension pack 
- [ ] Publish on VS Code Marketplace
```

## Open Questions: 
- Should we ensure that the extensions in the pack have the same release cycle and ideally version number?

**Comment by peterhnm** [comment]
@lmoesle An extension pack consists of only one package.json. Should I still create this under apps/? I don't have to build it but just copy the files into dist/. What is the best way to do that?

**Comment by lmoesle** [comment]
@peterhnm Good point. Nx is a javascript/typescript monorepo tool and for an extension pack we don't need it's capabilities. We could try it without nx or like you already mentioned include it into our apps structure.

1. Without Nx

Create a new folder in the repository with the extension packs package.json. Then we add a new script to `tools/scripts` which copies the package.json to the *dist* folder. This script needs to be triggered in the monorepos root package.json with the build command ( `npm run build`).

2. With Nx

We create a new app with just the extension packs package.json and a project.json. In the project.json we create a build target that just copies the file.
Note: The [`nx:run-commands`](https://nx.dev/packages/nx/executors/run-commands) executor may be useful for this task.

I don't really have an opion on what would be the better approach. Just pick the one that seems more intuitive to you.
