### ISSUE TITLE
[Feature] VS Code plugin to support DMN

### ISSUE THREAD

**Issue by Hafflgav** [FlowSquad/miranum-ide#137]
- [x] Description created
- [x] Reviewed by peer: @lmoesle 
- [x] Prioritised

# Description
As a process developer, I would like to be able to create bpmn processes in VS code.
- extend already existing VS code extension for process modeling
- .dmn files are automatically displayed in the editor
- The library https://github.com/FlowSquad/camunda-web-modeler can be used as a example
- Try to avoid adding React to the bpmn modeler
- Resources: [https://github.com/FlowSquad/miragon-process-ide/tree/main/resources](https://github.com/FlowSquad/miragon-process-ide/tree/main/resources)

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] Create new extension for DMN compatible with C7 and C8 models 
- [ ] Test and document new extension 
- [ ] Release extension
```
