### ISSUE TITLE
Provide revert capabilities for deployments

### ISSUE THREAD

**Issue by lmoesle** [FlowSquad/miranum-ide#146]
- [ ] Description created
- [ ] Reviewed by peer: 
- [ ] Prioritised

# Description

If I deploy multiple files to the digiwf-engine (via deployment-proxy) and some deployments fail and some succeed, I would like to revert the successful deployments to avoid a broken state.

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] Open an issue at digiwf-core to create a deployment revert api
- [ ] Implement the revert api in deployment-proxy
```

Note: We should wait until a revert deployment api is created in digiwf-core.

**Comment by lmoesle** [comment]
@dominikhorn93 What other artifacts do you mean? Should we just ignore the failed deployments and inform the user that their artifact is not valid?

**Comment by dominikhorn93** [comment]
It can be complicated to do a "revert" automatically. Maybe we did override a json schema and don't know which one was deployed before? I think we should just inform the user and show which artifacts fail.
In my point of view that is an ongoing "try and error" task until everything succeeds.

If a prod deployment fails the user should redeploy the last successful release.

**Comment by lmoesle** [comment]
Sounds good to me. The deployment proxy already implements this behavior. Therefore I will close this issue.
